services:
  - type: web
    name: trailerspot-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    branch: main
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
